spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/messenger"
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    encoding: UTF-8
    basename: "validation"